#' Construct a MoleculeExperiment
#'
#' @param molecules Detected transcripts information in a standardised ME list
#' format, as is generated by dataframeToMEList() and readMolecules() functions.
#' @param boundaries Slot with boundary information in a standardised ME list
#' format, as is generated by dataframeToMEList() and readBoundaries()
#' functions.
#' @rdname MoleculeExperiment-class
#' # TODO where to add this documentation?

#' @export
MoleculeExperiment <- function(molecules, boundaries = NULL) {
    me <- methods::new("MoleculeExperiment",
        molecules = molecules,
        boundaries = boundaries
    )
    return(me)
}
